
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/generated/l10n/*
    - lib/generated/l10n/intl/*
    - lib/generated/adapters/*/*
  
  errors:
    implicit_dynamic_parameter: false

linter:
  rules:
    always_specify_types: true
    omit_local_variable_types: false
    avoid_equals_and_hash_code_on_mutable_classes: false
    avoid_redundant_argument_values: false
    unawaited_futures: false
    sort_pub_dependencies: false
    one_member_abstracts: true
    public_member_api_docs: false
    avoid_print: true 