targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/engines/{{engine}}/models/{{file}}.dart': 'lib/generated/adapters/{{engine}}/{{file}}.dart'