targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{dir}}/models/{{file}}.dart': 'lib/generated/adapters/{{dir}}/{{file}}.dart'