name: islamy
description: A new islamic project that aims to provide the holy Quran in every language and anyother resources muslims would need.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  dio: ^4.0.4
  path_provider: ^2.0.9
  hive_flutter: ^1.1.0
  just_audio: ^0.9.20
  flutter_svg: ^1.0.3
  intl_utils: ^2.6.1
  iconsax: ^0.0.8
  pinput: ^2.2.3
  location: ^4.3.0
  permission_handler: ^9.2.0
  pubspec: ^2.1.0
  flag: ^6.0.0
  country_code_picker: ^2.0.2
  proper_filesize: ^0.0.2
  another_flushbar: ^1.10.28
  animations: ^2.0.2
  scrollable_positioned_list: ^0.2.3
  audio_service: ^0.18.4
  duration: ^3.0.11
  ffmpeg_kit_flutter_min: 4.5.1-LTS
  rxdart: ^0.27.3
  cupertino_icons: ^1.0.4
  sliver_bottom_bar:
    git: https://github.com/psyonixFx/sliver_bottom_bar.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  very_good_analysis: ^2.4.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/surah_icon.svg
    - assets/config/
  
  fonts:
    - family: QuranFont 1
      fonts:
        - asset: assets/fonts/Quran/QuranFont 1/font.ttf
    - family: QuranFont 2
      fonts:
        - asset: assets/fonts/Quran/QuranFont 2/font.ttf
    - family: QuranFont 3
      fonts:
        - asset: assets/fonts/Quran/QuranFont 3/font.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf

flutter_intl:
  arb_dir: l10n
  enabled: true
  output_dir: lib/generated/l10n
  main_locale: en_US
#  main_locale: ar