name: islamy
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  dio: ^4.0.4
  path_provider: ^2.0.9
  hive_flutter: ^1.1.0
  just_audio: ^0.9.20
  flip_widget: ^0.1.6
  flutter_svg: ^1.0.3
  intl_utils: ^2.6.1
  iconsax: ^0.0.8
  pinput: ^2.2.3
  location: ^4.3.0
  permission_handler: ^9.2.0
  pubspec: ^2.1.0
  flag: ^6.0.0
  country_code_picker: ^2.0.2
  proper_filesize: ^0.0.2
  another_flushbar: ^1.10.28
  animations: ^2.0.2
  scrollable_positioned_list: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.7

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/surah_icon.svg
    - assets/config/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: QuranFont 1
      fonts:
        - asset: assets/fonts/Quran/QuranFont 1/font.ttf
    - family: QuranFont 2
      fonts:
        - asset: assets/fonts/Quran/QuranFont 2/font.ttf
    - family: QuranFont 3
      fonts:
        - asset: assets/fonts/Quran/QuranFont 3/font.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  arb_dir: l10n
  enabled: true
  output_dir: lib/generated/l10n
  main_locale: en_US
#  main_locale: ar