name: islamy
description: A new islamic project that aims to provide the holy Quran in every language and anyother resources muslims would need.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # Plugins
  just_audio: ^0.9.20
  permission_handler: ^11.0.0
  location: ^5.0.3
  audio_service: ^0.18.4
  ffmpeg_kit_flutter_min: ^6.0.3

  # libs 
  path_provider: ^2.0.9
  intl: ^0.18.1
  dio: ^5.1.2
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.7
  iconsax: ^0.0.8
  pinput: ^3.0.1
  pubspec: ^2.1.0
  country_code_picker: ^3.0.0
  proper_filesize: ^0.0.2
  another_flushbar: ^1.10.28
  animations: ^2.0.2
  scrollable_positioned_list: ^0.3.8
  rxdart: ^0.27.3
  cupertino_icons: ^1.0.4
  sliver_bottom_bar:
    path: ../sliver_bottom_bar
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet
  flag: ^7.0.0
  super_cupertino_navigation_bar: ^1.1.0
  sliver_tools: ^0.2.12
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.1.7
  very_good_analysis: ^5.1.0
  intl_utils: ^2.8.5

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/surah_icon.svg
    - assets/config/
  
  fonts:
    - family: QuranFont 1
      fonts:
        - asset: assets/fonts/Quran/QuranFont 1/font.ttf
    - family: QuranFont 2
      fonts:
        - asset: assets/fonts/Quran/QuranFont 2/font.ttf
    - family: QuranFont 3
      fonts:
        - asset: assets/fonts/Quran/QuranFont 3/font.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf

flutter_intl:
  arb_dir: l10n
  enabled: true
  output_dir: lib/generated/l10n
  main_locale: en_US
#  main_locale: ar